language: node_js
node_js:
- 8.9.0
services:
- mongodb
env:
  global:
  - NODE_ENV=test
script:
- npm run test
cache:
  directories:
  - node_modules
deploy:
  provider: heroku
  app: interview-address-book
  repo: kovalenp/strv-interview-address-book
  api_key:
    secure: MUlkCKYzSAdRvNxFy/p8e2eC+pCtYKgPUdsz0D7EREYKb9qn3/Dlk8m4WMBEhr/FJzfTXomvFjuvyFCkV9NBxuzkXRA6dU8deX7Wcz5hBS4w0DTNt5pWUZEzGs25cswDCEaf+avit+LFo+63uw4m20Oz/fGPEuWOTmfH5624gRqgy7UYLDlhlBiFnr5YOkUCrxxl6xR5MrQw9YpeRa2eW1y89op0yuv33wMHzxaMhDlFp4hFB10cyQecq5h2/IfeYEOYeIXEZNfxHsoFX7xCXrUuVLoAQ7x+bkPsHMh5+vWWyD9Pn2RvoIORWycLBUsjtoR20JW5v7Z73fe0o0adT78DgdOCvwq9TedWcnt1hNUpGGmf10742gWebyYTbTpzpb/aRBnINh9x/6P6FWZ+DSKBEr+I/RjRSkAesRYlcUOXEor/fXLpl0fykhhoX89Wq4rwSbSwua0ywt2weHiHMipykl6zmh347X4m7LlU2VnEZRlzVMbjoh+xeIVKB+KBMX7abKMWYt37oZNzZx991rAub+Sv8KaczdXblDASYM4XqTzeMzQ0upngwCTgrJhd2xLrB80iagv9pnRzP26DAIUYcpzb41j/oCWgHkPk/5W8e/kbtR1Ive0HAWUi+LHQBWOAJyGub5ITMTnoGPHf1m5qgpR4ka7CIG8EWf8hjGo=
